### PR TITLE
Missing CellLocationController added to plugin.xml

### PR DESCRIPTION
**Pull request by mlegenhausen**
The `CellLocationController` is missing in the `config.xml` which leads to error during compilation.

### CODE REVIEW

**Comment by andygup** [comment]
Whoops. Excellent catch, thanks!

**Comment by andygup** [comment]
I'll update the CHANGELOG + version number for npm.

**Comment by mlegenhausen** [comment]
Thanks :) Thats a quick reaction!

**Comment by andygup** [comment]
I'm working on a related project and happened to be using this repo for some performance comparisons. Nothing like standing right on the starting line.

**Pull request merged**
