### PR TITLE
Don't return an invalid location when the cache is empty

### PR DESCRIPTION
**Pull request by mlegenhausen**
It makes no sense to return something that is completely invalid when nothing is in the cache. Bothering about default position should be part of the application not of this plugin.

### CODE REVIEW

**Comment by andygup** [comment]
Fair enough...that's legacy code from an alpha prototype. I see now it emitted erroneous information in the `accuracy` property as well.

I'll merge this then increment the version, update the API doc and push to npm.

**Comment by andygup** [comment]
Thanks for the pull request, btw! 

On a gentle side note reminder, it's a github best practice to do a pull request from a branch.

**Comment by andygup** [comment]
Also, will be making changes to NetworkLocationController which has the same issue.

**Comment by mlegenhausen** [comment]
Thanks for the advice do you have some documentation about best practice pull request?

**Comment by andygup** [comment]
Here's a decent [overview](https://yangsu.github.io/pull-request-tutorial/) of pull requests in general. If that's confusing one of the guys on our team has a really good tutorial and flow diagram somewhere that I can dig up.

Had a question for you. I have the shell script(s) and instructions I use to create the plugin's master AndroidStudio project. Do you think that would be useful for me to publish with the repo on github?

**Comment by mlegenhausen** [comment]
Thanks for the guide will take a look.

I would not add any IDE dependent files, cause it should be up to the developer which IDE he likes. Maybe he is more an eclipse fan. Take a look at editor independent configurations like (editorconfig)[http://editorconfig.org] if you want to provide some configurations.

**Pull request merged**
